# Generated by Django 4.2.13 on 2024-07-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_contact_us_email_alter_contact_us_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
